service: dvsa-rsp-public-portal

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: eu-west-1

functions:
  serveExpressApp:
    handler: handler.serveExpressApp
    events:
      - http: ANY /
      - http: "ANY /{proxy+}"
