# The AWSTemplateFormatVersion identifies the capabilities of the template
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: RSP Public portal
# Transform section specifies one or more macros that AWS CloudFormation uses to process your template

Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      DefinitionUri: ./simple-proxy-api.yml
      StageName: dev
      Variables:
        ServerlessExpressLambdaFunctionName: !Ref PublicPortalApiFunction

  PublicPortalApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: ./src/handler
      Runtime: nodejs16.x
      Architectures: [x86_64]
      MemorySize: 128
      Timeout: 100
      Description: The public portal to pay RSP
      Environment:
        Variables:
          USE_SECRETS_MANAGER: false
      Events:
        ProxyApiRoot:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /
            Method: ANY
        ProxyApiGreedy:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /{proxy+}
            Method: ANY

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Join
      - ''
      - - https://
        - !Ref ApiGatewayApi
        - ".execute-api."
        - !Ref AWS::Region
        - ".amazonaws.com/nonprod/"
#    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/NonProd/"
